apiVersion: v1
kind: Secret
metadata:
  name: cloud-credentials
  namespace: oadp-user1
stringData:
  cloud: |
    [default]
    aws_access_key_id=GKdb672e3e4fde02525e6c652c
    aws_secret_access_key=7f3294c63eed3cfd18e7d4f6e9a3cf42259992681cb55ab6f35daca7ecc95fe6
