apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/tracking-id: oadp-user1:oadp.openshift.io/DataProtectionApplication:oadp-user1/oadp-dpa
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"oadp.openshift.io/v1alpha1","kind":"DataProtectionApplication","metadata":{"annotations":{"argocd.argoproj.io/sync-options":"SkipDryRunOnMissingResource=true","argocd.argoproj.io/tracking-id":"oadp-user1:oadp.openshift.io/DataProtectionApplication:oadp-user1/oadp-dpa"},"name":"oadp-dpa","namespace":"oadp-user1"},"spec":{"backupLocations":[{"velero":{"config":{"profile":"default","region":"localstorage","s3ForcePathStyle":"true","s3Url":"to_be_set_by_job"},"credential":{"key":"cloud","name":"cloud-credentials"},"default":true,"objectStorage":{"bucket":"to_be_set_by_job","prefix":"velero"},"provider":"aws"}}],"configuration":{"velero":{"defaultPlugins":["csi","openshift","aws","kubevirt"],"featureFlags":["EnableCSI"]}}}}
  creationTimestamp: "2026-07-05T04:05:36Z"
  generation: 6
  name: oadp-dpa
  namespace: oadp-user1
  resourceVersion: "2348183"
  uid: a52c96cb-669c-4982-beeb-b3aaabcb7145
spec:
  backupLocations:
  - velero:
      config:
        checksumAlgorithm: ""
        profile: default
        region: garage
        s3ForcePathStyle: "true"
        s3Url: http://garage.poc-garage.svc.cluster.local:3900
      credential:
        key: cloud
        name: cloud-credentials
      default: true
      objectStorage:
        bucket: velero
        prefix: velero
      provider: aws
  configuration:
    velero:
      defaultPlugins:
      - csi
      - openshift
      - aws
      - kubevirt
      disableFsBackup: false
      featureFlags:
      - EnableCSI
  logFormat: text
status:
  conditions:
  - lastTransitionTime: "2026-07-13T17:50:50Z"
    message: Reconcile complete
    reason: Complete
    status: "True"
    type: Reconciled
