apiVersion: velero.io/v1
kind: Backup
metadata:
  name: poc-oadp-backup
  namespace: oadp-user1
spec:
  includedNamespaces:
    - poc-oadp
  storageLocation: oadp-dpa-1
  ttl: 720h0m0s
  snapshotVolumes: true
