apiVersion: console.openshift.io/v1
kind: ConsoleYAMLSample
metadata:
  name: poc-liveness-vm
spec:
  title: "POC VM Liveness/Readiness Probe"
  description: "A VirtualMachine example with HTTP Liveness/Readiness Probe configured. Performs periodic health checks on port 80, and restarts the VM after 3 consecutive failures."
  targetResource:
    apiVersion: kubevirt.io/v1
    kind: VirtualMachine
  yaml: |
    apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    metadata:
      name: poc-liveness-vm
      namespace: poc-liveness-probe
    spec:
      runStrategy: Always
      template:
        spec:
          readinessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
            successThreshold: 3
          livenessProbe:
            httpGet:
              port: 80
            initialDelaySeconds: 120
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
          domain:
            cpu:
              cores: 1
            memory:
              guest: 2Gi
            devices:
              disks:
                - name: rootdisk
                  disk:
                    bus: virtio
          volumes:
            - name: rootdisk
              dataVolume:
                name: poc-liveness-vm
      dataVolumeTemplates:
        - metadata:
            name: poc-liveness-vm
          spec:
            pvc:
              accessModes:
                - ReadWriteMany
              resources:
                requests:
                  storage: 30Gi
            sourceRef:
              kind: DataSource
              name: poc
              namespace: openshift-virtualization-os-images
